import Header from "components/Header";
import Hero from "components/Hero";
import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div className="bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory overflow-y-scroll overflow-x-hidden z-0 ">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/**Header */}

      <Header />
      <section id="hero" className="snap-start">
        <Hero />
      </section>
    </div>
  );
}
